### ISSUE TITLE
ERROR whatBump is not a function

### ISSUE THREAD

**Issue by splincode** [release-it/release-it#1168]
After upgrade to 17.10
https://github.com/taiga-family/configurations/pull/673

I have failed job

https://github.com/taiga-family/configurations/actions/runs/11384045613/job/31670932627

<img width="632" alt="image" src="https://github.com/user-attachments/assets/39713b72-f2f9-4f4d-9d28-532b7de26b60">

my release it config:
https://github.com/taiga-family/configurations/blob/main/projects/release-it-config/index.js
